# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-16 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialNetwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodel',
            name='text',
            field=models.TextField(max_length=6000),
        ),
    ]
