# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-16 07:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialNetwork', '0002_auto_20180516_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
