# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-26 15:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialNetwork', '0002_auto_20180426_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodel',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
