# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-26 16:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialNetwork', '0004_auto_20180426_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=5000)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='groupAdmin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='postsmodel',
            old_name='created_data',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='profilemodel',
            old_name='created_data',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='postsmodel',
            name='group',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='mobile',
            field=models.CharField(default=0, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='posts',
            field=models.ManyToManyField(blank=True, to='socialNetwork.PostsModel'),
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
