# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-15 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialNetwork', '0007_profilemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='image',
            field=models.FileField(default='profile/profile.png', upload_to='profile/'),
        ),
    ]
